name: easeim_flutter_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    
  # 通讯录 listView
  azlistview:
    git:
      url: https://github.com/dujiepeng/azlistview.git
      ref: master

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # 数据缓存
  shared_preferences: ^0.5.12+4

  # 状态共享
  provider: ^4.3.2+3

  # 汉字转拼音
  # lpinyin: ^1.1.0

  # 侧滑删除
  flutter_slidable: ^0.5.7

  # 下拉刷新
  pull_to_refresh: 1.6.3

  # 屏幕适配
  flutter_screenutil: 4.0.3+1

  # 常用工具类
  flustars: ^0.3.2

  # 滚动列表，可以根据index滚动到指定位置
  # scroll_to_index: ^1.0.6

  # 页面路由, 目前看demo跳转比较简单，可以不用。
  # fluro: ^1.7.8

  # 监听键盘弹起
  keyboard_visibility: ^0.5.6

  # 图片选择
  image_picker: ^0.6.7+17

  # 存储图片
  image_gallery_saver: '^1.6.7'
  # 拼音
  # lpinyin: ^1.1.0

  # 文件选择
  #file_picker: ^2.1.4

  # 元组
  tuple: ^1.0.3

  # 权限管理
  permission_handler: ^5.0.1+1

  # dialog
  flutter_smart_dialog: ^1.2.6

  # 显示占位符图片
  transparent_image: ^1.0.0

  # 长按菜单
  w_popup_menu: ^0.3.1

  # 环信 sdk
  im_flutter_sdk:
      path: ../

  # 音频录制转换和播放
  record_amr:
      git:
        url: https://github.com/dujiepeng/record_amr.git
        ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - menu_up_arrow.png

    - images/logo.png
    - images/launch.jpg
    - images/login_bg.jpg
    - images/login_icon.png
    - images/login_pwd_show.png
    - images/login_pwd_hidden.png
    - images/login_usename_clear.png
    - images/login_protocal_selected.png
    - images/login_protocal_unselected.png    
    
    - images/register_back.png

    - images/home_tab_chat.png
    - images/home_tab_contact.png
    - images/home_tab_me.png
    - images/home_tab_selected_chat.png
    - images/home_tab_selected_contact.png
    - images/home_tab_selected_me.png

    - images/chat_input_bar_close.png
    - images/chat_input_bar_emoji.png
    - images/chat_input_bar_keyboard.png
    - images/chat_input_bar_more_show.png
    - images/chat_input_bar_more_close.png
    - images/chat_input_bar_voice_hidden.png
    - images/chat_input_bar_voice_show.png
    - images/chat_input_more_call.png
    - images/chat_input_more_camera.png
    - images/chat_input_more_file.png
    - images/chat_input_more_loc.png
    - images/chat_input_more_photo.png
    - images/chat_input_more_video.png
    - images/chat_input_more_pin.png

    - images/chat_bubble_img_broken.png
    - images/chat_bubble_voice_ripple00.png
    - images/chat_bubble_voice_ripple01.png
    - images/chat_bubble_voice_ripple02.png
    
    - images/chat_faces_delete.png
    
    - images/contact_default_avatar.png
    
    - images/expression/
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
